- name: Install Server Dependencies
  run: |
    cd Server
    npm install

- name: Install Client Dependencies and Build
  run: |
    cd Client
    npm install
    npm run build

- name: Upload artifact for deployment job
  uses: actions/upload-artifact@v4
  with:
    name: node-app
    path: Server
